Fixed webroot-absolute image resource paths
WatchBeam/implicit-oauth-example pull request #2
Opened 2017-04-20 18:44 UTC by Metaa

2017-05-28 22:06 UTC, ProbablePrime approved these changes

2017-05-28 22:47 UTC, jamesbirtles requested changes
Screenshot pls

2017-05-28 22:47 UTC, UnwrittenFun commented on README.md
> +They click accept and are then forwarded back to your url where they will see their token:
trailing spaces

2017-05-28 22:47 UTC, UnwrittenFun commented on README.md
> +User visits link `interactive.example.com/request` and sees the OAuth Page:
trailing spaces

2017-05-28 22:47 UTC, UnwrittenFun commented on app.js
> +	document.querySelector(".hint .onerror").classList.add('show');
check indent

2017-05-28 22:47 UTC, UnwrittenFun commented on style.css
> +.hint a {
Keep 1 new line before each block

2017-05-28 22:49 UTC, Metaa commented
The intentionally placed trailing spaces cause a newline in Markdown so that the images are properly wrapped, even though GitHub wraps them anyways because of the width of the site :)

2017-05-28 23:14 UTC, Metaa commented
Screenshots:
![image](https://cloud.githubusercontent.com/assets/5056880/26532832/1f293634-440c-11e7-9744-b55a9fa52ab6.png)
![image](https://cloud.githubusercontent.com/assets/5056880/26532833/259f4f9e-440c-11e7-8ea8-3f5f0ea169b9.png)

2017-05-28 23:15 UTC, Metaa commented on README.md
> +User visits link `interactive.example.com/request` and sees the OAuth Page:
That's a markdown linebreak to wrap the image

2017-05-28 23:15 UTC, Metaa commented on README.md
> +They click accept and are then forwarded back to your url where they will see their token:
That's a markdown linebreak to wrap the image

2017-05-28 23:25 UTC, cactysman reviewed
Requested changes included in latest commit

Screenshots:
![image](https://cloud.githubusercontent.com/assets/5056880/26532832/1f293634-440c-11e7-9744-b55a9fa52ab6.png)
![image](https://cloud.githubusercontent.com/assets/5056880/26532833/259f4f9e-440c-11e7-8ea8-3f5f0ea169b9.png)

2017-05-29 00:50 UTC, ProbablePrime approved these changes

2017-05-29 12:06 UTC, jamesbirtles approved these changes

2017-05-29 12:16 UTC, Metaa commented
Remember to also replace "Beam" with "Mixer" in the repository description. 🙂

2017-05-29 12:24 UTC, merged